name: Deploy Frontend to Azure Static Web Apps

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Add debug step to check directory
      - name: Debug Directory
        run: |
          pwd
          ls -la

      - name: Install Dependencies
        run: |
          npm ci
          echo "Dependencies installed"
          ls -la

      # Add environment file creation step
      - name: Create Production Environment File
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" > .env.production
          echo "VITE_PAYMENT_API_URL=${{ secrets.VITE_PAYMENT_API_URL }}" >> .env.production
          echo "VITE_PAYPAL_CLIENT_ID=${{ secrets.VITE_PAYPAL_CLIENT_ID }}" >> .env.production
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env.production
          echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> .env.production
          echo "Environment file created"
          cat .env.production

      - name: Build
        run: |
          npm run build
          echo "Build completed"
          ls -la dist/
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          VITE_PAYMENT_API_URL: ${{ secrets.VITE_PAYMENT_API_URL }}
          VITE_PAYPAL_CLIENT_ID: ${{ secrets.VITE_PAYPAL_CLIENT_ID }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

      # Add debug step after build
      - name: Debug Build Output
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Dist directory contents:"
          ls -la dist/ || echo "dist directory not found"

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # Change this to root directory
          output_location: "dist" # Change this to where the build output is
          skip_app_build: false # Change to false to let Azure build
          app_build_command: "npm run build" # Specify the build command
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          VITE_PAYMENT_API_URL: ${{ secrets.VITE_PAYMENT_API_URL }}
          VITE_PAYPAL_CLIENT_ID: ${{ secrets.VITE_PAYPAL_CLIENT_ID }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
