name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment (adjust version as needed)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # 3. Install dependencies using a lock file for consistency
      - name: Install dependencies
        run: npm ci
        # If you don't have a lock file, you can alternatively use:
        # run: npm install

      # 4. Build the Vite React application
      - name: Build project
        run: npm run build

      # 5. Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # Adjust the app_location and output_location based on your project structure:
          app_location: "/" # Location of your app (root if it's a single-page app)
          output_location: "dist" # Default Vite output directory (adjust if different)
